/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as ProfileSlugImport } from './routes/profile/$slug'
import { Route as ProfileProfileIdEditImport } from './routes/profile/$profileId/edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileSlugRoute = ProfileSlugImport.update({
  id: '/profile/$slug',
  path: '/profile/$slug',
  getParentRoute: () => rootRoute,
} as any)

const ProfileProfileIdEditRoute = ProfileProfileIdEditImport.update({
  id: '/profile/$profileId/edit',
  path: '/profile/$profileId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$slug': {
      id: '/profile/$slug'
      path: '/profile/$slug'
      fullPath: '/profile/$slug'
      preLoaderRoute: typeof ProfileSlugImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$profileId/edit': {
      id: '/profile/$profileId/edit'
      path: '/profile/$profileId/edit'
      fullPath: '/profile/$profileId/edit'
      preLoaderRoute: typeof ProfileProfileIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/profile/$profileId/edit': typeof ProfileProfileIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/profile/$slug'
  | '/login'
  | '/register'
  | '/profile/$profileId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/profile/$slug'
  | '/login'
  | '/register'
  | '/profile/$profileId/edit'
  id:
  | '__root__'
  | '/'
  | '/profile/$slug'
  | '/login/'
  | '/register/'
  | '/profile/$profileId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileSlugRoute: typeof ProfileSlugRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ProfileProfileIdEditRoute: typeof ProfileProfileIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileSlugRoute: ProfileSlugRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ProfileProfileIdEditRoute: ProfileProfileIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile/$slug",
        "/login/",
        "/register/",
        "/profile/$profileId/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile/$slug": {
      "filePath": "profile/$slug.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/profile/$profileId/edit": {
      "filePath": "profile/$profileId/edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
